=== FASSi-bit/LaVuelta2026/xml/etapa.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">
	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="numero" />
				<xs:element ref="longitud-etapa" />
				<xs:element ref="fecha" />
				<xs:element ref="tiempo-ganador" />
				<xs:element ref="velocidad-ganador" />
				<xs:element ref="desnivel" />
				<xs:element ref="ciudad-inicio" />
				<xs:element ref="ciudad-meta" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="podcasts" />
				<xs:element ref="lugar-salida" />
				<xs:element ref="lugar-meta" />
				<xs:element ref="hitos" />
				<xs:element ref="puntos-anon" />
				<xs:element ref="clasificados-etapa" />
				<xs:element ref="clasificados-general" />
				<xs:element ref="equipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="numero" type="xs:nonNegativeInteger" />
	<xs:element name="longitud-etapa">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="tiempo-ganador" type="xs:duration" />
	<xs:element name="velocidad-ganador">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ciudad-inicio" type="xs:string" />
	<xs:element name="ciudad-meta" type="xs:string" />
	<xs:element name="tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			<xs:enumeration value="Montaña" />
			<xs:enumeration value="Llana" />
			<xs:enumeration value="Contrarreloj individual" />
			<xs:enumeration value="Contrarreloj por equipos"/>
			<xs:enumeration value="Media montaña"></xs:enumeration>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="podcasts">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="podcast" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="podcast" type="xs:string" />
	<xs:element name="lugar-salida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lugar-meta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="puerto-montaña" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="sprint-bonificado" />
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="sprint-intermedio" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puerto-montaña">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tipo-puerto" />
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distancia-salida" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprint-bonificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distancia-salida" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprint-intermedio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distancia-salida" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntos-anon">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto-anon" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto-anon">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="nombre-punto" />
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distancia-salida" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificados-etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="clasificado-etapa" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado-etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre-clasificado" />
				<xs:element ref="equipo" />
				<xs:element ref="tiempo-clasificado" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia-tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificados-general">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="clasificado-general" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado-general">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre-clasificado" />
				<xs:element ref="equipo" />
				<xs:element ref="tiempo-clasificado" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia-tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="equipo-clasificacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipo-clasificacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre-equipo" />
				<xs:element ref="tiempo-equipo" />
				<xs:element minOccurs="0" maxOccurs="1" ref="diferencia-tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoLongitud">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-180.0"/>
            <xs:maxInclusive value="180.0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Latitud: entre -90.0 y 90.0 grados -->
    <xs:simpleType name="tipoLatitud">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-90.0"/>
            <xs:maxInclusive value="90.0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Altitud: mayor o igual a 0 metros (o un límite negativo realista como -500.0) -->
    <xs:simpleType name="tipoAltitud">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Distancia: valores no negativos (>= 0.0) -->
    <xs:simpleType name="tipoDistancia">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>



	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLongitud">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLatitud">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAltitud">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia-salida">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDistancia">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre-punto" type="xs:string" />
	<xs:element name="tipo-puerto" >
		<xs:simpleType>
				<xs:restriction base="xs:string">
				<xs:enumeration value="Primera categoría" />
				<xs:enumeration value="Segunda categoría" />
				<xs:enumeration value="Tercera categoría" />
				<xs:enumeration value="Categoría especial"/>
				<xs:enumeration value="Bonificado">	 
				</xs:enumeration>
				</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre-clasificado" type="xs:string" />
	<xs:element name="equipo" type="xs:string" />
	<xs:element name="tiempo-clasificado" type="xs:duration" />
	<xs:element name="diferencia-tiempo" type="xs:duration" />
	<xs:element name="nombre-equipo" type="xs:string" />
	<xs:element name="tiempo-equipo" type="xs:duration" />
</xs:schema>

=== FASSi-bit/LaVuelta2026/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    <nombre>Carrefour Granada - Granada</nombre>
    <numero>21</numero>
    <longitud-etapa unidades="kilómetros">112</longitud-etapa>
    <fecha>2026-09-13</fecha>
    <tiempo-ganador>PT03H07M09S</tiempo-ganador>
    <velocidad-ganador unidades="Km/h">35.9</velocidad-ganador>
    <desnivel unidades="metros">1217</desnivel>
    <ciudad-inicio>Carrefour Granada</ciudad-inicio>
    <ciudad-meta>Granada</ciudad-meta>
    <tipo>Llana</tipo>
    <referencias>
        <referencia>https://www.lavuelta.es/es/etapa-21</referencia>
        <referencia>Libro de Ruta La Vuelta 2026</referencia>
        <referencia>https://www.esciclismo.com/actualidad/carretera/93042.html</referencia>
        <referencia>https://www.ivoox.com/vuelta-2026-etapa-21-audios-mp3_rf_180499626_1.html</referencia>
    </referencias>
    <fotos>
        <foto>Foto-ganador-etapa.jpg</foto>
        <foto>Entrada-ganador-general.jpg</foto>
        <foto>Grupo-corredores.jpg</foto>
    </fotos>
    <videos>
        <video>LastKm-Stage21_LaVuelta26.mp4</video>
    </videos>
    <podcasts>
        <podcast>Podcast-oficial-LaVuelta2026.mp3</podcast>
    </podcasts>
    <!-- Coordenadas reales de Granada para la Salida y Meta -->
    <lugar-salida>
        <longitud unidades="grados">-3.6079</longitud>
        <latitud unidades="grados">37.1550</latitud>
        <altitud unidades="metros">664.0</altitud>
    </lugar-salida>
    <lugar-meta>
        <longitud unidades="grados">-3.5931</longitud>
        <latitud unidades="grados">37.1698</latitud>
        <altitud unidades="metros">670.6</altitud>
    </lugar-meta>
    
    <hitos>
        <sprint-intermedio>
            <longitud unidades="grados">-3.5942</longitud>
            <latitud unidades="grados">37.1697</latitud>
            <altitud unidades="metros">669.0</altitud>
            <distancia-salida unidades="kilómetros">92.4</distancia-salida>
        </sprint-intermedio>
    </hitos>
    
    <puntos-anon>
        <punto-anon>
            <nombre-punto>Salida Vuelta</nombre-punto>
            <longitud unidades="grados">-3.6079</longitud>
            <latitud unidades="grados">37.1550</latitud>
            <altitud unidades="metros">664.0</altitud>
            <distancia-salida unidades="kilómetros">0.0</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6073</longitud>
            <latitud unidades="grados">37.1546</latitud>
            <altitud unidades="metros">664.0</altitud>
            <distancia-salida unidades="kilómetros">0.1</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6074</longitud>
            <latitud unidades="grados">37.1545</latitud>
            <altitud unidades="metros">664.0</altitud>
            <distancia-salida unidades="kilómetros">0.1</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6072</longitud>
            <latitud unidades="grados">37.1543</latitud>
            <altitud unidades="metros">664.0</altitud>
            <distancia-salida unidades="kilómetros">0.1</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6068</longitud>
            <latitud unidades="grados">37.1548</latitud>
            <altitud unidades="metros">665.6</altitud>
            <distancia-salida unidades="kilómetros">0.2</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6090</longitud>
            <latitud unidades="grados">37.1560</latitud>
            <altitud unidades="metros">662.3</altitud>
            <distancia-salida unidades="kilómetros">0.4</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6096</longitud>
            <latitud unidades="grados">37.1558</latitud>
            <altitud unidades="metros">662.6</altitud>
            <distancia-salida unidades="kilómetros">0.5</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6123</longitud>
            <latitud unidades="grados">37.1532</latitud>
            <altitud unidades="metros">663.0</altitud>
            <distancia-salida unidades="kilómetros">0.8</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6125</longitud>
            <latitud unidades="grados">37.1526</latitud>
            <altitud unidades="metros">663.0</altitud>
            <distancia-salida unidades="kilómetros">0.9</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6130</longitud>
            <latitud unidades="grados">37.1524</latitud>
            <altitud unidades="metros">663.4</altitud>
            <distancia-salida unidades="kilómetros">0.9</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6107</longitud>
            <latitud unidades="grados">37.1458</latitud>
            <altitud unidades="metros">668.4</altitud>
            <distancia-salida unidades="kilómetros">1.7</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6202</longitud>
            <latitud unidades="grados">37.1383</latitud>
            <altitud unidades="metros">675.0</altitud>
            <distancia-salida unidades="kilómetros">2.9</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6355</longitud>
            <latitud unidades="grados">37.1420</latitud>
            <altitud unidades="metros">669.1</altitud>
            <distancia-salida unidades="kilómetros">4.3</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6377</longitud>
            <latitud unidades="grados">37.1418</latitud>
            <altitud unidades="metros">669.4</altitud>
            <distancia-salida unidades="kilómetros">4.5</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6398</longitud>
            <latitud unidades="grados">37.1431</latitud>
            <altitud unidades="metros">666.8</altitud>
            <distancia-salida unidades="kilómetros">4.8</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6519</longitud>
            <latitud unidades="grados">37.1467</latitud>
            <altitud unidades="metros">657.0</altitud>
            <distancia-salida unidades="kilómetros">6.0</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6518</longitud>
            <latitud unidades="grados">37.1506</latitud>
            <altitud unidades="metros">651.2</altitud>
            <distancia-salida unidades="kilómetros">6.4</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6443</longitud>
            <latitud unidades="grados">37.1511</latitud>
            <altitud unidades="metros">650.0</altitud>
            <distancia-salida unidades="kilómetros">7.1</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6306</longitud>
            <latitud unidades="grados">37.1493</latitud>
            <altitud unidades="metros">654.0</altitud>
            <distancia-salida unidades="kilómetros">8.3</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6263</longitud>
            <latitud unidades="grados">37.1499</latitud>
            <altitud unidades="metros">656.0</altitud>
            <distancia-salida unidades="kilómetros">8.7</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6217</longitud>
            <latitud unidades="grados">37.1533</latitud>
            <altitud unidades="metros">654.0</altitud>
            <distancia-salida unidades="kilómetros">9.2</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6136</longitud>
            <latitud unidades="grados">37.1532</latitud>
            <altitud unidades="metros">661.6</altitud>
            <distancia-salida unidades="kilómetros">10.0</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6105</longitud>
            <latitud unidades="grados">37.1457</latitud>
            <altitud unidades="metros">668.4</altitud>
            <distancia-salida unidades="kilómetros">10.9</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6089</longitud>
            <latitud unidades="grados">37.1464</latitud>
            <altitud unidades="metros">670.0</altitud>
            <distancia-salida unidades="kilómetros">11.1</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6080</longitud>
            <latitud unidades="grados">37.1469</latitud>
            <altitud unidades="metros">673.0</altitud>
            <distancia-salida unidades="kilómetros">11.2</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6064</longitud>
            <latitud unidades="grados">37.1449</latitud>
            <altitud unidades="metros">675.0</altitud>
            <distancia-salida unidades="kilómetros">11.5</distancia-salida>
        </punto-anon>
        <punto-anon>
            <longitud unidades="grados">-3.6043</longitud>
